-- DESABILITAR RLS TEMPORARIAMENTE PARA TESTES
-- Execute este SQL no SQL Editor do Supabase

ALTER TABLE clientes DISABLE ROW LEVEL SECURITY;

ALTER TABLE vendas DISABLE ROW LEVEL SECURITY;

ALTER TABLE recebimentos DISABLE ROW LEVEL SECURITY;

ALTER TABLE pagamentos DISABLE ROW LEVEL SECURITY;

ALTER TABLE notas_fiscais DISABLE ROW LEVEL SECURITY;

-- Mensagem de sucesso
SELECT 'RLS desabilitado para todas as tabelas!' AS status;